### ISSUE TITLE
Inertia Hello World app won't start

### ISSUE THREAD

**Issue by lectrician1** [adonisjs/create-adonisjs#6]
### Package version

idk

### Describe the bug

node v22.5.0
run `npm init adonisjs@latest hello-world`
select inertia, skip auth, sqlite, svelte, skip server side

after done installing run `npm run start` the app won't open on localhost:3333

also the scripts are wrong that are generated like npm start it's "js" files instead of ts and when you manully change it to ts you get
`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"`

**Comment by RomainLanz** [comment]
Hey @lectrician1! 👋🏻 

`npm run start` is for starting the production server, in development, you should use `npm run dev`.

You can also start the server manually using `node ace serve`.

📚 https://docs.adonisjs.com/guides/getting-started/installation#starting-the-development-server

**Comment by lectrician1** [comment]
npm run dev is actually the command that works and starts the server, but then I go to localhost:3333 it doesn't load

**Comment by lectrician1** [comment]
Oh i see my issue. my app is running in a dev container and I need to expose the app on 0.0.0.0
